## lib/Makefile -------------------------------------------------*- Makefile -*-

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile. The order is
# relevant.
#
DIRS =  PrologEngineWrapper \
	PrologEngineWrapper_DeclExtractorBuild \
	DeclExtractor \
	CrispClangPlugin \
	CrispLLVMPass

include $(LEVEL)/Makefile.common
