## lib/Makefile -------------------------------------------------*- Makefile -*-

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS= PrologEngineWrapper CrispClangPlugin CrispLLVMPass

include $(LEVEL)/Makefile.common
