##===- projects/crisp/data/PrologBootForCrispClangPlugin/Makefile -*- Makefile -*-

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=

PROLOGSAVEDSTATENAME=PrologBootForCrispClangPlugin

include $(LEVEL)/Makefile.common
